//! Best-effort export of a loop to an equivalent standalone bash script.
//!
//! The in-Rust runner is the primary path; this is a convenience for CI or for
//! sharing a loop where installing `cloop` isn't worth it. Complex permission
//! or tool specs may need manual quoting in the generated FLAGS line.

use crate::config::{LoopConfig, StopKind};

/// Single-quote a string for safe embedding in bash.
fn sh(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// Produce a bash script that approximates running this loop.
pub fn to_bash(cfg: &LoopConfig) -> String {
    let mut s = String::new();
    s.push_str("#!/usr/bin/env bash\n");
    s.push_str("# Generated by cloop — an equivalent loop as a portable shell script.\n");
    s.push_str("set -uo pipefail\n\n");

    s.push_str(&format!("cd {} || exit 1\n\n", sh(&cfg.workdir)));

    s.push_str(&format!("MAX={}\n", cfg.max_iterations));
    s.push_str(&format!("TASK={}\n", sh(&cfg.task)));
    match cfg.stop_kind {
        StopKind::Command => s.push_str(&format!("CHECK={}\n", sh(&cfg.stop_command))),
        StopKind::Marker => s.push_str(&format!("MARKER={}\n", sh(&cfg.stop_marker))),
        StopKind::Iterations => {}
    }
    s.push('\n');

    // Static flags (everything except --continue and the positional prompt).
    let mut flags: Vec<String> = vec!["--print".to_string()];
    if !cfg.model.is_empty() {
        flags.push("--model".into());
        flags.push(cfg.model.clone());
    }
    if cfg.skip_permissions {
        flags.push("--dangerously-skip-permissions".into());
    } else if !cfg.permission_mode.is_empty() {
        flags.push("--permission-mode".into());
        flags.push(cfg.permission_mode.clone());
    }
    if cfg.max_turns > 0 {
        flags.push("--max-turns".into());
        flags.push(cfg.max_turns.to_string());
    }
    if !cfg.allowed_tools.is_empty() {
        flags.push("--allowedTools".into());
        flags.push(cfg.allowed_tools.clone());
    }
    if !cfg.extra_args.is_empty() {
        flags.push(cfg.extra_args.clone());
    }
    s.push_str(&format!("FLAGS=\"{}\"\n\n", flags.join(" ")));

    s.push_str("for ((i=1; i<=MAX; i++)); do\n");
    s.push_str("  echo \"── iteration $i / $MAX ──\"\n");
    if cfg.carry_context {
        s.push_str("  cont=\"\"; [ \"$i\" -gt 1 ] && cont=\"--continue\"\n");
    } else {
        s.push_str("  cont=\"\"\n");
    }

    match cfg.stop_kind {
        StopKind::Command => {
            s.push_str("  if [ \"$i\" -eq 1 ]; then\n");
            s.push_str("    prompt=\"$TASK\"\n");
            s.push_str("  else\n");
            s.push_str("    prompt=\"Iteration $i of $MAX. The check '$CHECK' is still failing. Its output was:\n\n$out\n\nDiagnose and fix it with concrete edits.\"\n");
            s.push_str("  fi\n");
            s.push_str("  claude $FLAGS $cont \"$prompt\"\n");
            s.push_str("  if out=\"$(eval \"$CHECK\" 2>&1)\"; then\n");
            s.push_str("    echo \"check passed on iteration $i\"; exit 0\n");
            s.push_str("  fi\n");
        }
        StopKind::Marker => {
            s.push_str("  if [ \"$i\" -eq 1 ]; then\n");
            s.push_str("    prompt=\"$TASK\n\nWhen fully complete, print the exact line $MARKER on its own line.\"\n");
            s.push_str("  else\n");
            s.push_str("    prompt=\"Iteration $i of $MAX. Continue. When fully complete, print the exact line $MARKER on its own line.\"\n");
            s.push_str("  fi\n");
            s.push_str("  output=\"$(claude $FLAGS $cont \"$prompt\")\"\n");
            s.push_str("  echo \"$output\"\n");
            s.push_str("  if printf '%s' \"$output\" | grep -qF \"$MARKER\"; then\n");
            s.push_str("    echo \"marker seen on iteration $i\"; exit 0\n");
            s.push_str("  fi\n");
        }
        StopKind::Iterations => {
            s.push_str("  if [ \"$i\" -eq 1 ]; then\n");
            s.push_str("    prompt=\"$TASK\"\n");
            s.push_str("  else\n");
            s.push_str("    prompt=\"Iteration $i of $MAX. Continue working on the task.\"\n");
            s.push_str("  fi\n");
            s.push_str("  claude $FLAGS $cont \"$prompt\"\n");
        }
    }

    if cfg.delay_secs > 0 {
        s.push_str(&format!("  sleep {}\n", cfg.delay_secs));
    }
    s.push_str("done\n\n");

    match cfg.stop_kind {
        StopKind::Iterations => s.push_str("echo \"completed $MAX iterations\"\n"),
        _ => {
            s.push_str("echo \"reached MAX without satisfying the stop condition\" >&2\n");
            s.push_str("exit 1\n");
        }
    }

    s
}
